export const railChartData = {
    data: {
      datasets: [
            {
            "day": "1",
            "empty": 3,
            "loaded": 3,
            "arriving": 5
              }, {
            "day": "2",
            "Empty": 2,
            "loaded": 7,
            "arriving": 2
              }, {
            "day": "3",
            "Empty": 3,
            "loaded": 4,
            "arriving": 1
               }, {
            "day": "4",
            "empty": 1,
            "loaded": 3,
            "arriving": 5
              }, {
            "day": "5",
            "Empty": 2,
            "loaded": 7,
            "arriving": 2
              }, {
            "day": "6",
            "empty": 3,
            "loaded": 1,
            "arriving": 1
              }, {
            "day": "7",
            "Empty": 2,
            "loaded": 2,
            "arriving": 2
              }, {
              "day": "8",
            "empty": 3,
            "loaded": 3,
            "arriving": 1
              }, {
            "day": "9",
            "Empty": 2,
            "loaded": 1,
            "arriving": 2
              }, {
            "day": "10",
            "empty": 3,
            "loaded": 3,
            "arriving": 1
              }, {
            "day": "11",
            "Empty": 2,
            "loaded": 3,
            "arriving": 2
              }, {
            "day": "12",
            "empty": 3,
            "loaded": 3,
            "arriving": 5
              }, {
            "day": "13",
            "Empty": 2,
            "loaded": 7,
            "arriving": 2
              },{
            "day": "14",
            "empty": 1,
            "loaded": 3,
            "arriving": 5
              }, {
            "day": "15",
            "Empty": 2,
            "loaded": 7,
            "arriving": 2
              }, {
            "day": "16",
            "empty": 3,
            "loaded": 1,
            "arriving": 1
              }, {
            "day": "17",
            "Empty": 2,
            "loaded": 2,
            "arriving": 2
              }, {
              "day": "18",
            "empty": 3,
            "loaded": 3,
            "arriving": 1
              }, {
            "day": "19",
            "Empty": 2,
            "loaded": 1,
            "arriving": 2
              }, {
            "day": "20",
            "empty": 3,
            "loaded": 3,
            "arriving": 1
              }, {
            "day": "21",
            "Empty": 2,
            "loaded": 3,
            "arriving": 2
              }, {
            "day": "22",
            "empty": 3,
            "loaded": 3,
            "arriving": 5
              }, {
            "day": "23",
            "Empty": 2,
            "loaded": 7,
            "arriving": 2
              }, {
            "day": "24",
            "empty": 1,
            "loaded": 3,
            "arriving": 5
              }, {
            "day": "25",
            "Empty": 2,
            "loaded": 7,
            "arriving": 2
              }, {
            "day": "26",
            "empty": 3,
            "loaded": 1,
            "arriving": 1
              }, {
            "day": "27",
            "Empty": 2,
            "loaded": 2,
            "arriving": 2
              }, {
              "day": "28",
            "empty": 3,
            "loaded": 3,
            "arriving": 1
              }, {
            "day": "29",
            "Empty": 2,
            "loaded": 1,
            "arriving": 2
              }, {
            "day": "30",
            "empty": 3,
            "loaded": 3,
            "arriving": 1
              }, 
      ]
    },
    options: {
      responsive: true,
      lineTension: 1,
      scales: {
        yAxes: [
          {
            ticks: {
              beginAtZero: true,
              padding: 25
            }
          }
        ]
      }
    }
  };
  
  export default railChartData;